### ISSUE TITLE
How to disable roll?

### ISSUE THREAD

**Issue by Lampadina17** [MasahideMori-SimpleAppli/simple_3d_renderer#9] opened 2023-09-27 21:32 UTC
how i can disable roll?

**Comment by MasahideMori-SimpleAppli** [comment] 2023-09-28 03:05
Hi @Lampadina17 ,

If you want to suppress world rotation caused by user operations, set the Sp3dRenderer argument allowUserWorldRotation to false.
Also, if you want to suppress zooming caused by the user's mouse scroll, etc., also set allowUserWorldZoom to false.

**Comment by Lampadina17** [comment] 2023-09-28 11:15
i want keep yaw, i want keep pitch and clamp 180 deg and disable roll

**Comment by MasahideMori-SimpleAppli** [comment] 2023-09-28 12:00
Do you want to rotate an object by specifying an axis?
For now, let's set the coordinate system as (roll, pich, yaw) = (x axis, y axis, z axis) = (right direction, upward direction, front direction).
To rotate 180 degrees around the x-axis:

```
// Rotate the object around the origin (0,0,0)
Sp3dObj obj = UtilSp3dGeometry.cube(200, 200, 200, 1, 1, 1);
obj.rotate(Sp3dV3D(1, 0, 0).nor(), 180 * Sp3dConstantValues.toRadian);
```

```
// Rotate object in place
Sp3dObj obj = UtilSp3dGeometry.cube(200, 200, 200, 1, 1, 1);
obj.rotateInPlace(Sp3dV3D(1, 0, 0).nor(), 180 * Sp3dConstantValues.toRadian);
```

Please note that to try this code you will need to import the following packages:
[import 'package:util_simple_3d/util_simple_3d.dart';](https://pub.dev/packages/util_simple_3d)

**Comment by Lampadina17** [comment] 2023-09-28 20:26
im not sure that roting model solve the issue, my model correctly moves as expected but i only need to disable camera roll

https://github.com/MasahideMori-SimpleAppli/simple_3d_renderer/assets/32492054/a9b802b1-6c0a-423e-8adb-a49ebae8a24c

**Comment by MasahideMori-SimpleAppli** [comment] 2023-09-29 08:19
That's a very cool video!
In your case, I think it is best to set the allowUserWorldRotation argument of Sp3dRenderer to false, and then rotate the object using Sp3dObj's rotate method.
If the Sp3dRenderer argument allowUserWorldRotation is false, the object will not be rotated by user interaction (such as mouse dragging or swiping).
Therefore, I think the object will be displayed fixed in the orientation you rotated in the program.

**Comment by MasahideMori-SimpleAppli** [comment] 2023-10-05 04:45
Has the problem been resolved?
For now, I would like to close this issue.
If my answer does not have enough functionality, please consider extending Sp3dCameraRotationController.
Thank you!

**Closed as completed by MasahideMori-SimpleAppli** 2023-10-05 04:45 UTC
Labels: question
